version: '3'

services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./backend:/var/www
      - ./service-bring-citymail:/var/services/service-bring-citymail
      - ./service-deutschepost:/var/services/service-deutschepost
      - ./service-asendia:/var/services/service-asendia
      - ./service-dhl-express:/var/services/service-dhl-express
      - ./service-dhl-freight-v2:/var/services/service-dhl-freight-v2
      - ./service-earlybird:/var/services/service-earlybird
      - ./service-postnord-v2:/var/services/service-postnord-v2
    depends_on:
      - db
      - redis
      - nginx
#      - node
    container_name: stinder_app
    networks:
      - internal

  nginx:
    image: nginx:latest
    volumes:
      - ./backend:/var/www
      - ./_docker/rootfs/etc/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    container_name: stinder_nginx
    networks:
      - internal

  db:
    image: mysql:8.0.33
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    container_name: stinder_db
    networks:
      - internal

  redis:
    image: redis:alpine
    container_name: stinder_redis
    labels:
      SERVICE_NAME: stinder_redis
    networks:
      - internal
#  node:
#    build:
#      context: .
#      dockerfile: _docker/node/Dockerfile
#    volumes:
#      - ./frontend:/var/www
#    ports:
#      - "80:8080"
#    container_name: stinder_node
#    networks:
#      - internal

networks:
  internal:
    driver: bridge